# Generated by Django 3.2.5 on 2021-07-08 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='snippet',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(max_length=100)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.snippet')),
            ],
        ),
    ]
