# Generated by Django 3.2.5 on 2021-07-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210707_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='snippet',
        ),
        migrations.AddField(
            model_name='tag',
            name='snippets',
            field=models.ManyToManyField(to='app.Snippet'),
        ),
    ]
