# Generated by Django 3.2.5 on 2021-07-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210708_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='snippets',
        ),
        migrations.AddField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(to='app.Tag'),
        ),
    ]
