# Generated by Django 3.2.5 on 2021-07-09 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210708_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique id for a particular snippet', primary_key=True, serialize=False),
        ),
    ]
