# Generated by Django 3.2.5 on 2021-07-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_snippet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
