# Generated by Django 3.2.5 on 2021-08-26 19:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_snippet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
