# Generated by Django 3.2.5 on 2021-08-26 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210826_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='uuid',
            new_name='id',
        ),
    ]
